version: '3'
services:
   auth:
      build: docker/AuthenticationService
      image: auth
      hostname: auth
      container_name: auth
      depends_on:
        - esregistry
        - mysqldb
      networks:
       - ms_network
      ports:
       - 8001:8001
      command: -jar AuthenticationService.jar 8001 auth esregistry:9200
   celsius:
      build: docker/CelsiusService
      image: celsius
      hostname: celsius
      container_name: celsius
      depends_on:
        - esregistry
      networks:
       - ms_network
      ports:
       - 8002:8002
      command: -jar CelsiusService.jar 8002 celsius esregistry:9200
   celsius2:
      build: docker/CelsiusService
      image: celsius
      hostname: celsius2
      container_name: celsius2
      depends_on:
        - esregistry
      networks:
       - ms_network
      ports:
       - 8005:8005
      command: -jar CelsiusService.jar 8005 celsius2 esregistry:9200  
   goweb:
      build: Go/goweb
      image: goweb
      hostname: goweb
      container_name: goweb
      depends_on:
        - esregistry
      networks:
       - ms_network
      ports:
       - 8080:8080
   esregistry:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.1
    hostname: esregistry
    container_name: esregistry
    networks:
       - ms_network
    environment:
      - cluster.name=esregistrycluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
   mysqldb:
    image: mysql
    hostname: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: testuser, test
    networks:
     - ms_network
    ports:
      - 3306:3306 
volumes:
  esdata1:
    driver: local
    
networks:
  ms_network:
    driver: bridge