version: '3'

services:
   auth:
      build: ./AuthenticationService
      image: auth
      hostname: auth
      container_name: auth
      networks:
       - ms_network
      ports:
       - 8001:8001 
      command: -jar AuthenticationService.jar 8001 esregistry:9200
      
   celsius:
      build: ./CelsiusService
      image: celsius
      hostname: celsius
      container_name: celsius
      networks:
       - ms_network
      ports:
       - 8002:8002 
      command: -jar CelsiusService.jar 8002 esregistry:9200
      
   esregistry:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.1
    hostname: esregistry
    container_name: esregistry
    networks:
       - ms_network
    environment:
      - cluster.name=esregistrycluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      
volumes:
  esdata1:
    driver: local

networks:
  ms_network:
    driver: bridge